//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServerFinalApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int OrderNr { get; set; }
        public string Ansvarig { get; set; }
        public string Avdelning { get; set; }
        public Nullable<int> Prioritet { get; set; }
        public string Börjat { get; set; }
        public Nullable<System.DateTime> Klar { get; set; }
        public string BildFormat { get; set; }
    
        public virtual Avdelningar Avdelningar { get; set; }
        public virtual Elever Elever { get; set; }
    }
}
